// app/backend/src/prisma/seed.ts
import { PrismaClient, RecoveryPlanCategory } from "@prisma/client";

const prisma = new PrismaClient();

/**
 * Deterministic seed:
 * - Always upserts the exact template version we intend to serve (v2)
 * - Always uses the same JSON objects
 * - Optional stable demo activation codes (enabled by env flag)
 */
async function main() {
  // ✅ Seed the template version you are serving (v2)
  const template = await prisma.recoveryPlanTemplate.upsert({
    where: {
      category_version: {
        category: RecoveryPlanCategory.general_outpatient,
        version: 2,
      },
    },
    update: {
      title: "General Outpatient Recovery Plan (Educational)",
      planJson: defaultGeneralOutpatientPlanJsonV2(),
      sourcesJson: defaultSourcesJson(),
    },
    create: {
      category: RecoveryPlanCategory.general_outpatient,
      version: 2,
      title: "General Outpatient Recovery Plan (Educational)",
      planJson: defaultGeneralOutpatientPlanJsonV2(),
      sourcesJson: defaultSourcesJson(),
    },
  });

  // ✅ Optional deterministic demo activation codes
  // Turn on only when you want them:
  //   SEED_DEMO_CODES=true pnpm -C app/backend exec prisma db seed
  const seedDemoCodes = (process.env.SEED_DEMO_CODES ?? "").toLowerCase() === "true";

  const demoCodes = ["FR-DEMO-0001", "FR-DEMO-0002", "FR-DEMO-0003"] as const;

  if (seedDemoCodes) {
    for (const code of demoCodes) {
      await prisma.activationCode.upsert({
        where: { code },
        update: {}, // never overwrite a claimed code
        create: {
          code,
          clinicTag: "local-test",
          // status defaults to UNUSED if your schema does that
        },
      });
    }
  }

  console.log("✅ Seed complete");
  console.log("Template:", {
    id: template.id,
    category: template.category,
    version: template.version,
    title: template.title,
    sourcesJsonPresent: template.sourcesJson != null,
  });

  if (seedDemoCodes) {
    console.log("Demo Activation Codes:", demoCodes);
  } else {
    console.log("Demo Activation Codes: (skipped) set SEED_DEMO_CODES=true to seed");
  }
}

/**
 * Sources are for educational reference only.
 * (These should be general, non-prescriptive, and NOT clinic-specific medical instructions.)
 */
function defaultSourcesJson() {
  return {
    schemaVersion: 1,
    source: "MedlinePlus",
    links: [
      {
        title: "Surgical wound care (general information)",
        url: "https://medlineplus.gov/surgicalwoundcare.html",
      },
      {
        title: "Pain medicines (general information)",
        url: "https://medlineplus.gov/painrelievers.html",
      },
      {
        title: "Preventing infections (general information)",
        url: "https://medlineplus.gov/infectioncontrol.html",
      },
    ],
    disclaimer:
      "Educational information only. Not medical advice. Always follow your surgeon/clinician’s instructions. If you have urgent symptoms, contact your clinician or seek emergency care.",
  };
}

/**
 * Template planJson is NOT your generated patient plan.
 * Your “brain” (engine) generates the actual plan stored on RecoveryPlan.planJson.
 *
 * This is still useful as:
 * - a stable placeholder contract
 * - a place to version template-level metadata if needed later
 */
function defaultGeneralOutpatientPlanJsonV2() {
  return {
    schemaVersion: 2,
    templateName: "general_outpatient",
    notes: "Template placeholder. Actual plan is generated by engineVersion v1.",
    days: [],
  };
}

main()
  .catch((e) => {
    console.error("❌ Seed failed", e);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
